---
log:
  level: DEBUG
  format: json
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
         entryPoint:
           to: "websecure"
           scheme: "https"
  websecure:
    address: ":443"

providers:
  file:
    filename: /etc/traefik/file-provider.yaml

certificatesResolvers:
  acmetls:
    acme:
      email: mail@maltewildt.de
      storage: /etc/traefik/acme/acme.json
      httpChallenge:
        entryPoint: web
